apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: test
spec:
  selector:
    app: eureka-server
  clusterIP: None
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP