apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-server
  namespace: test
data:
  eureka-server-defaultZone: "http://eureka-server-0:8080/eureka,http://eureka-server-0:8080/eureka,http://eureka-server-0:8080/eureka"
  eureka-server: "http://eureka-server/eureka"