apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-server
  namespace: test
data:
  eureka-server: "http://eureka-server-0.eureka-server.test:8080/eureka,http://eureka-server-1.eureka-server.test:8080/eureka,http://eureka-server-2.eureka-server.test:8080/eureka"