spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_SERVER:http://127.0.0.1:8080/eureka}
  instance:
    appname: ${EUREKA_INSTANCE_NAME:${spring.application.name}}
    instance-id: ${EUREKA_INSTANCE_ID:${spring.application.name}}